version: '3' #Docker-compose version
services: # Lista de servicios
  flask_app: #servicio/app de flask
    build: # Lista de parámetros desde los cuales construir
      context: . #contexto
      dockerfile: Dockerfile #nombre de archivo de Dockerfile
    ports: #puerto contenedor:puerto host
      - "5005:5005"
    restart: always #en caso de error o falla. Es como una práctica comun user este
    # Con Docker Compose